/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/slots/fetch/many": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get paginated list of slots (from ClickHouse) */
		post: operations["SlotsController_fetchMany"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/slots/fetch/one/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get slot by ID (from Mongo) */
		get: operations["SlotsController_fetchOne"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/slots": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a new slot */
		post: operations["SlotsController_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/slots/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update slot */
		patch: operations["SlotsController_update"];
		trace?: never;
	};
	"/slots/{id}/deactivate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Deactivate slot */
		post: operations["SlotsController_deactivate"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/slots/{id}/book": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Book a slot (create booking) */
		post: operations["SlotsController_book"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/bookings/fetch/many": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get paginated list of bookings (from ClickHouse) */
		post: operations["BookingsController_fetchMany"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/bookings/fetch/one/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get booking by ID (from Mongo) */
		get: operations["BookingsController_fetchOne"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/bookings/{id}/cancel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Cancel booking */
		post: operations["BookingsController_cancel"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login and get JWT token */
		post: operations["AuthController_login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		SortingDto: {
			/** @description Field to sort by */
			id: string;
			/** @description Sort direction */
			desc?: boolean;
		};
		ColumnFilterDto: {
			/** @description Filter field ID */
			id: string;
			/** @description Filter value(s) */
			value: Record<string, never>;
			/** @description Filter function (in, contains) */
			filterFn: string;
		};
		DateRangeDto: {
			/** @description Start date (ISO 8601) */
			from: string;
			/** @description End date (ISO 8601) */
			to: string;
			/** @description Date field name */
			field: string;
			/** @description Timezone */
			timezone?: string;
		};
		FetchManyDto: {
			/** @description Page index (0-based) */
			pageIndex: number;
			/** @description Page size */
			pageSize: number;
			/** @description Sorting configuration */
			sorting: components["schemas"]["SortingDto"][];
			/** @description Column filters */
			columnFilters: components["schemas"]["ColumnFilterDto"][];
			/** @description Date range filter */
			dateRange?: components["schemas"]["DateRangeDto"];
		};
		Slot: {
			/** @description MongoDB document ID */
			mongoId: string;
			/** @description Slot title */
			title: string;
			/**
			 * Format: date-time
			 * @description Slot start time
			 */
			startsAt: string;
			/** @description Maximum capacity */
			capacity: number;
			/** @description Current booked count */
			bookedCount: number;
			/** @description Whether slot is active */
			isActive: boolean;
			/**
			 * Format: date-time
			 * @description Creation timestamp
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @description Last update timestamp
			 */
			updatedAt: string;
		};
		SlotsListResponse: {
			data: components["schemas"]["Slot"][];
			totalCount: number;
		};
		CreateSlotDto: {
			/** @description Slot title */
			title: string;
			/** @description Slot start time (ISO 8601) */
			startsAt: string;
			/** @description Maximum capacity */
			capacity: number;
		};
		UpdateSlotDto: {
			/** @description Slot title */
			title?: string;
			/** @description Slot start time (ISO 8601) */
			startsAt?: string;
			/** @description Maximum capacity */
			capacity?: number;
		};
		CreateBookingDto: {
			/** @description Client name */
			clientName: string;
			/** @description Client email */
			clientEmail: string;
		};
		Booking: {
			/** @description MongoDB document ID */
			mongoId: string;
			/** @description Slot ID reference */
			slotId: string;
			/** @description Denormalized slot title at booking time */
			slotTitle: string;
			/**
			 * Format: date-time
			 * @description Denormalized slot start time at booking time
			 */
			slotStartsAt: string;
			/** @description Client name */
			clientName: string;
			/** @description Client email (lowercased) */
			clientEmail: string;
			/**
			 * @description Booking status
			 * @enum {string}
			 */
			status: "ACTIVE" | "CANCELLED";
			/**
			 * Format: date-time
			 * @description Creation timestamp
			 */
			createdAt: string;
			/**
			 * Format: date-time
			 * @description Last update timestamp
			 */
			updatedAt: string;
		};
		BookingsListResponse: {
			data: components["schemas"]["Booking"][];
			totalCount: number;
		};
		LoginDto: {
			/** @description Admin login */
			login: string;
			/** @description Admin password */
			password: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	SlotsController_fetchMany: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["FetchManyDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SlotsListResponse"];
				};
			};
		};
	};
	SlotsController_fetchOne: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Slot"];
				};
			};
		};
	};
	SlotsController_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateSlotDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Slot"];
				};
			};
		};
	};
	SlotsController_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateSlotDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Slot"];
				};
			};
		};
	};
	SlotsController_deactivate: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Slot"];
				};
			};
		};
	};
	SlotsController_book: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateBookingDto"];
			};
		};
		responses: {
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Booking"];
				};
			};
		};
	};
	BookingsController_fetchMany: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["FetchManyDto"];
			};
		};
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BookingsListResponse"];
				};
			};
		};
	};
	BookingsController_fetchOne: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Booking"];
				};
			};
		};
	};
	BookingsController_cancel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Booking"];
				};
			};
		};
	};
	AuthController_login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginDto"];
			};
		};
		responses: {
			/** @description JWT token */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						token?: string;
					};
				};
			};
			/** @description Invalid credentials */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}
